services:
  mariadb:
    image: mariadb:10.6.18
    ports:
      - '3306:3306'
    environment:
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}

  app:
    build: ./
    profiles: [windows]
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
